# Generated by Django 4.0.5 on 2022-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='value',
        ),
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.CharField(choices=[('offers_ms', 'Offers Ms'), ('product_ms', 'Product Ms')], default='product_ms', max_length=10),
        ),
    ]
